# Generated by Django 5.1.7 on 2025-05-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=100, verbose_name='Title')),
                ('description', models.TextField(help_text='Description', max_length=512, verbose_name='Description')),
                ('date', models.DateField(help_text='Date', verbose_name='Date')),
            ],
        ),
    ]
