# Generated by Django 5.1.7 on 2025-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Job Title', max_length=100, verbose_name='Job Title')),
                ('contract_type', models.CharField(help_text='Contract Type', max_length=100, verbose_name='Contract Type')),
                ('company_name', models.CharField(help_text='Company Name', max_length=100, verbose_name='Company Name')),
                ('description', models.CharField(help_text='Description', max_length=512, verbose_name='Description')),
                ('start_date', models.DateField(help_text='Start Date', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='End Date', verbose_name='End Date')),
            ],
        ),
    ]
