# Generated by Django 5.1.7 on 2025-05-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='localisation',
            field=models.CharField(default='France', help_text='Company Localisation', max_length=100, verbose_name='Company Localisation'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(help_text='Description', max_length=512, verbose_name='Description'),
        ),
    ]
