# Generated by Django 5.1.7 on 2025-05-14 04:02

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_experience_localisation_alter_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='banner',
            field=models.FileField(help_text='Banner Image of the experience', null=True, upload_to='experience_banner', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='contract_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CDI', 'CDI'), ('INTERNSHIP', 'Stage')], help_text='The Type of the Contract signed', max_length=255, verbose_name='Contract Type'),
        ),
    ]
