# Generated by Django 5.1.7 on 2025-05-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_experiencetask'),
        ('skill', '0010_skill_color_skill_display_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencetask',
            name='skill',
        ),
        migrations.AddField(
            model_name='experiencetask',
            name='skills',
            field=models.ManyToManyField(help_text='Skills', to='skill.skill', verbose_name='Skills'),
        ),
        migrations.CreateModel(
            name='ExperienceSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(help_text='Experience', on_delete=django.db.models.deletion.CASCADE, to='experience.experience', verbose_name='Experience')),
                ('skill', models.ForeignKey(help_text='Skill', on_delete=django.db.models.deletion.CASCADE, to='skill.skill', verbose_name='Skill')),
            ],
        ),
    ]
