# Generated by Django 5.1.7 on 2025-05-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_remove_experiencetask_skill_experiencetask_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencetask',
            name='tooltip',
            field=models.CharField(default='tete', help_text='Tooltip HelpText', max_length=256, verbose_name='Tooltip HelpText'),
            preserve_default=False,
        ),
    ]
