# Generated by Django 5.1.7 on 2025-05-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_alter_experiencetask_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencetask',
            name='description',
            field=models.TextField(help_text='Experience Description', max_length=124, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='experiencetask',
            name='tooltip',
            field=models.TextField(help_text='Tooltip HelpText', max_length=512, verbose_name='Tooltip HelpText'),
        ),
    ]
