# Generated by Django 5.1.7 on 2025-05-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0008_alter_experiencetask_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencetask',
            name='importance',
            field=models.IntegerField(default=0, help_text='How important was this task and should it be displayed on top or bottom of the list ?', verbose_name='Level of Importance'),
        ),
    ]
