# Generated by Django 5.1.7 on 2025-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0009_experiencetask_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='contract_type',
            field=models.CharField(choices=[('CDI', 'CDI'), ('INTERNSHIP', 'Stage')], default='CDI', help_text='The Type of the Contract signed', max_length=20, verbose_name='Contract Type'),
        ),
    ]
