# Generated by Django 5.1.7 on 2025-06-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0010_alter_experience_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(help_text='Description', max_length=2048, verbose_name='Description'),
        ),
    ]
