# Generated by Django 5.1.7 on 2025-05-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='SKill Title', max_length=100, verbose_name='Title')),
                ('description', models.TextField(help_text='Skill Header', max_length=4096, verbose_name='Header')),
                ('icon', models.FileField(help_text='Icon of the skill', null=True, upload_to='icon', verbose_name='Icon')),
            ],
        ),
    ]
