# Generated by Django 5.1.7 on 2025-05-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='description',
            field=models.TextField(help_text='Description', max_length=4096, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='title',
            field=models.CharField(help_text='Title', max_length=100, verbose_name='Title'),
        ),
    ]
