# Generated by Django 5.1.7 on 2025-05-13 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0002_alter_hobby_description_alter_hobby_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Le titre de l'image", max_length=100, verbose_name='Titre')),
                ('file', models.FileField(help_text='Une Image Associée à mon hobby', null=True, upload_to='hobby_image', verbose_name='Image liée a mon hobby')),
                ('movie', models.ForeignKey(help_text="Le hobby associé à l'image", on_delete=django.db.models.deletion.CASCADE, to='hobby.hobby', verbose_name='Hobby')),
            ],
        ),
    ]
