# Generated by Django 5.1.7 on 2025-05-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0003_hobbyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobbyimage',
            old_name='movie',
            new_name='hobby',
        ),
    ]
