# Generated by Django 5.1.7 on 2025-05-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0004_rename_movie_hobbyimage_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='icon',
        ),
        migrations.AddField(
            model_name='hobby',
            name='banner',
            field=models.FileField(help_text='Banner Image of the skill', null=True, upload_to='hobby_icon', verbose_name='Banner'),
        ),
    ]
