# Generated by Django 5.1.7 on 2025-05-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0005_remove_hobby_icon_hobby_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='banner',
            field=models.FileField(help_text='Banner Image of the hobby', null=True, upload_to='hobby_banner', verbose_name='Banner'),
        ),
    ]
