# Generated by Django 5.1.7 on 2025-05-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='SKill Title', max_length=100, verbose_name='Title')),
                ('header', models.TextField(help_text='Skill Header', max_length=4096, verbose_name='Header')),
            ],
        ),
        migrations.CreateModel(
            name='SkillSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Skill Section Text', max_length=8192, verbose_name='Text')),
                ('skill', models.ForeignKey(help_text='The Skill associated with the section', on_delete=django.db.models.deletion.CASCADE, to='skill.skill', verbose_name='Skill')),
            ],
        ),
    ]
