# Generated by Django 5.1.7 on 2025-05-13 00:47

import skill.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.SmallIntegerField(default=1, help_text='SKill Level', validators=[skill.models.validate_skill], verbose_name='Level'),
        ),
    ]
