# Generated by Django 5.1.7 on 2025-05-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.FileField(help_text='Icon of the skill', null=True, upload_to='ixon', verbose_name='Icon'),
        ),
    ]
