# Generated by Django 5.1.7 on 2025-05-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(help_text='Icon of the skill', null=True, upload_to='icon', verbose_name='Icon'),
        ),
    ]
