# Generated by Django 5.1.7 on 2025-05-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_alter_skill_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='header',
            new_name='description',
        ),
    ]
