# Generated by Django 5.1.7 on 2025-05-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_rename_header_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='banner',
            field=models.FileField(help_text='Banner Image of the skill', null=True, upload_to='skill_banner', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(help_text='Icon of the skill', null=True, upload_to='skill_icon', verbose_name='Icon'),
        ),
    ]
