# Generated by Django 5.1.7 on 2025-05-14 19:12

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0006_skill_banner_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='mode',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SOFT', 'SOFT'), ('HARD', 'HARD')], default='HARD', help_text='Is the Skill a hard skill or a soft skill', max_length=255, verbose_name='Skill Mode'),
        ),
    ]
