# Generated by Django 5.1.7 on 2025-05-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0007_skill_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='mode',
            field=models.CharField(choices=[('SOFT', 'SOFT'), ('HARD', 'HARD')], default='HARD', help_text='Is the Skill a hard skill or a soft skill', max_length=64, verbose_name='Skill Mode'),
        ),
    ]
