# Generated by Django 5.1.7 on 2025-05-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_alter_skill_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='example',
            field=models.TextField(blank=True, help_text='Skill Example', max_length=4096, verbose_name='Example'),
        ),
        migrations.AddField(
            model_name='skill',
            name='tips',
            field=models.TextField(blank=True, help_text='Skill Tips', max_length=4096, verbose_name='Tips'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Skill Header', max_length=4096, verbose_name='Header'),
        ),
    ]
