# Generated by Django 5.1.7 on 2025-05-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0010_skill_color_skill_display_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(blank=True, help_text='Skill Color for Banner', max_length=6, verbose_name='Color'),
        ),
    ]
