name: Test Unit

on:
  push


env:
  AWS_REGION: eu-central-1                 
  ECR_REPOSITORY: service   
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read  

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Set up Python 3.9.21
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.21

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test

